app/main.py

In #15 i wrote about making changes for support submitting POST data via browser extension. After little research I understood that my problem can be solved by supporting CORS rules. 
In this PR i added middleware for supporting `Origin` header in request. Also i added one more handler for `OPTIONS` pre-request which make by browser.
I tested that solution in my environment and also i create extension for Google Chrome https://github.com/Rpsl/metube-browser-extension

Add support of CORS rules

---

app/dl_formats.py

Not every audio container has support for thumbnails, so I put it under mp3.
Also, the `ytdl_opts["postprocessors"]` was growing with every download (mutating the parameter is bad), so I fixed that bug too.

Try downloading metadata/thumbnails for mp3 files automatically

---

app/main.py
app/ytdl.py
ui/src/app/app.component.html
ui/src/app/downloads.service.ts

This adds a simple download link that points to the downloaded file.
Note: This makes all files in the download directory (and its
sub-directory) available to any user.
Closes #26

Add download link to downloaded file

---

app/ytdl.py
ui/src/app/downloads.service.ts

closes #214.
also closes #124 and closes #139 as long as you use an `OUTPUT_TEMPLATE` like `%(title)s.%(epoch)s.%(ext)s` to uniquify the downloaded filename.

unique downloads of identically named videos

---

app/dl_formats.py
app/ytdl.py
ui/src/app/app.component.ts
ui/src/app/formats.ts

This PR add m4a audio format support that is native to many ytb videos and could avoid transcoding. 
Also replaces the "Any" format, with explicit format selector which will also drive the quality selector.

Add m4a support and explicit audio format

---

README.md

The one linked in README has been removed due to violation.
Replaced the link with https://github.com/kairi003/Get-cookies.txt-LOCALLY Chrome store ver.

Replace Chrome cookies extractor with get-cookiestxt-locally in README

---

Dockerfile
app/ytdl.py

Previously when downloading age restricted video from YouTube you got the error "PermissionError: [Errno 13] Permission denied: '/.cache'" from yt-dlp. This pull request fixes it by creating the necessary directory with the correct permissions in the container.

Fix error because of missing cache directory

---

README.md
app/main.py
app/ytdl.py

Hi @alexta69,
thanks for the awesome work here.
I introduced two new environment options:
* DELETE_FILE_ON_TRASHCAN to fix #108 
* DOWNLOAD_DIRS_INDEXABLE to make the downloads dir indexable (which I would like)
If any of this does not suite your standards or you want to have the things in separate PRs, just let me know.
Thanks and have a nice sunday!

Introduce environment options DELETE_FILE_ON_TRASHCAN and DOWNLOAD_DIRS_INDEXABLE

---

README.md
app/main.py

Dark mode can be set to the default theme by setting 'DARK_MODE' environment variable to `true`
#171

Add default theme option

---

app/ytdl.py

Not being able to delete the file should not stop the clearance from the download list.
One error I encountered, is when failed downloads have no dl.info.filename attribute. It was impossible to delete these entries from the "Completed" section.

Fix issues with deleting files with DELETE_FILE_ON_TRASHCAN

---

ui/src/app/app.component.html
ui/src/app/app.component.ts
ui/src/app/downloads.service.ts

The arguments passed to `retryDownload` by the retry button do not match what the function actually expects. This causes a few issues:
- Downloads break if a custom folder is set
- Format and custom name prefix are not applied to the retried download
This PR fixes these problems by passing the entire download object to `retryDownload`, which now populates everything correctly. The `Download` interface was also updated to include all the fields actually sent by the server.
Fixes #233, #262

Fix retry button issues

---

ui/src/app/app.component.html
ui/src/app/app.component.ts

Currently angular is re-rendering the entire download queue whenever a download's state changes. 
This is inefficient, but when combined with a long download queue the frequency of websocket progress updates causes many thousands of dom nodes to be created very quickly. This causes a large increase in memory usage, which in my experience continues to worsen until the tab is closed.
This PR adds a `trackBy` function to the `ngFor` of each half of the queue to resolve this by preventing unnecessary re-rendering.
Fixes #297

Fix memory leak when many videos are queued

---

README.md
app/main.py

This PR implements a way to load yt-dlp custom options from file using the same environment variable name, i also updated the README.md to reflect the changes.
This PR closes #210

Support loading YTDL_OPTIONS from file

---

README.md
app/main.py
ui/angular.json
ui/src/app/app.component.html
ui/src/app/app.component.sass
ui/src/app/app.component.ts
ui/src/app/theme.ts
ui/src/styles.sass

The theme switcher is updated to include an auto mode to follow the system setting
and I updated the dark theme to utilize bootstrap 5's build in support for dark mode theming.
The __DARK_MODE__ environment setting would always override the clients selected theme, this setting is now renamed to __DEFAULT_THEME__ and only sets a default theme when no other theme is selected, witch was likely the original creators intent.

Better dark theme and theme switcher

---

app/ytdl.py
ui/src/app/app.component.html

Hi, 
This pull request add support for showing when the live stream will start as error message.
to support getting past the format error as not yet live stream throw an error i had to use `ignore_no_formats_error` option.

Added support for showing when live stream will start as error message

---

app/ytdl.py

Fixes #363 
In some cases, such as when writing thumbnails, this call can still cause creation of non-temporary files on disk which should then also be placed in DOWNLOAD_DIR

Pass paths also when extracting metadata

---

ui/src/custom-service-worker.js
ui/src/manifest.webmanifest

In my recent PR for the PWA share target I made a mistake with absolute instead of relative paths. This lead to incorrect behavior with URL paths other than root.
This PR fixes that and adds a short comment to the URL RegExp as discussed (https://github.com/alexta69/metube/pull/361#discussion_r1438685903).

Fix PWA manifest for relative paths

---

app/ytdl.py
ui/src/app/app.component.html
ui/src/app/app.module.ts
ui/src/app/downloads.pipe.ts

This PR addresses Issue #322 by adding the functionality to display file sizes on the downloads page. The changes have been implemented in both the backend and frontend of the application.
- Updated API endpoints to return file size information.
- Implemented efficient file size calculation.
- Modified the downloads page to include file size display.
- Adjusted UI elements to accommodate file size information, ensuring readability and design consistency.

Implement File Size Display on Downloads Page - Resolves #322

---

app/ytdl.py
ui/src/app/app.component.html
ui/src/app/app.module.ts
ui/src/app/downloads.pipe.ts

Currently, users cannot cancel or delete tasks if they haven't been started automatically. This PR implements proper handling for non-started downloads, allowing users to cancel and delete them before downloading begins. This also resolves the "requested cancel for non-existent download" warning.

Fix cancellation & deletion for non-started downloads (#383)

---

README.md

Updated the MeTube bookmarklet to include `xhr.withCredentials=true` in the AJAX request. This allows the bookmarklet to work when MeTube is behind basic auth.
Only applied this change to the Chrome version of the bookmarklet since that is the environment I was able to test in.
Thank you for metube 📺

Support basic auth in Chrome bookmarklet

---

app/dl_formats.py

To avoid unnecessary conversion, yt-dlp can try to download the requested format first.

Don't convert audio if necessary

---

README.md
app/dl_formats.py
ui/src/app/formats.ts

The iOS-compatible video may not be the best quality. Add a separate quality option to accommodate people who want the best available versus the best compatible with iOS's strict requirements.
Testing with https://www.youtube.com/watch?v=YiRMs5ZhcH4 where the best quality video is 2160p and not iOS-compatible.
With best quality, the VP9 video format is used (better quality but not iOS-compatible):
```
% ffprobe -hide_banner Who\ Can\ Find\ the\ Weirdest\ PC\ Parts\ on\ AliExpress？.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Who Can Find the Weirdest PC Parts on AliExpress？.mp4':
Metadata:
major_brand     : isom
minor_version   : 512
compatible_brands: isomiso2mp41
encoder         : Lavf60.16.100
Duration: 00:19:02.72, start: 0.000000, bitrate: 10941 kb/s
Stream #0:0[0x1](und): Video: vp9 …
```

Add separate quality entry for iOS compatibility

---

ui/src/index.html

Fixes: #470
I tested both Firefox and Chromium, with and without proxy.
After changing the manifest origin setting, on Firefox everything works correctly.
Sadly, Chromium still has problems, issues are open for years now.
In any case, the fix shouldn't have impact on users without basic auth and respects the spec.

Fix basic auth not asking for credentials

---

README.md

Removed line `version: "3"` from Docker Compose YAML example. Specifying version is now obsolete and will throw a warning message when launching docker compose file.

removed version line from Docker Compose YAML section

---

ui/src/app/app.component.html
ui/src/app/app.component.sass

This pull request implements a few layout and style tweaks to the UI to improve usability on smaller screen sizes. 
- Fixed theme dropdown being positioned incorrectly at small screen sizes
- Additional breakpoint for the 3 dropdowns and button below the URL input
- Fixed advanced options dropdown overflowing past the left edge of the page
- Tweaked advanced options dropdown contents layout to put the switch at the bottom and give the input next to it enough room
- Moved buttons that were the headers of their tables to give them more room so that they no longer wrap awkwardly inside the table
- Moved buttons at the end of each table row into a shared cell to make their spacing consistent
- Download progress bar now appears below the video title at small screen sizes

Responsive design improvements

---

app/ytdl.py

Issue: When trying to download any series from tubitv, there is an error that appears and I'm not able to download the series. I am able to download individual videos from within the playlist.
Reason: When creating the DownloadInfo object, there is an error thrown due to the title not existing on the entry. Adding a fallback fixes this error and allows things to proceed as expected.

fix: provide default value for title when absent

---

ui/ngsw-config.json

The Service Worker caches the index.html file. When MeTube is behind an auth proxy, the browser opens index.html from the cache instead of returning a 401 status(in the case of basic auth) or redirecting for OAuth2 forward proxies(such as Authelia, Authentik, OAuth2-Proxy, etc).
This PR excludes index.html from the Service Worker, ensuring that the first request is always fresh and returns the correct status code.
This addresses the following issues:
- https://github.com/alexta69/metube/issues/478
- https://github.com/alexta69/metube/issues/459

Exclude index.html from service worker

---

Dockerfile

I noticed that the docker container was slow to shut down, just a little over 10 seconds. This is a strong indication that the sigint signal is not getting forwarded to subprocesses properly, and the container only shuts down once it receives sigkill. This is easily fixed by using `tini` as the entrypoint, which will, among other things, handle the signals properly. 
Here is an example before and after adding `tini`:

Add tini as entrypoint in Dockerfile

---

app/main.py
ui/src/app/app.component.html
ui/src/app/app.component.ts

In order to clearly know the current yt-dlp version in use and to distinguish whether the issue is known to yt-dlp, the current yt-dlp version number is displayed at the bottom of the web page.

display yt-dlp version in webui

---

app/ytdl.py

In case the user tries to restart the container with an updated container but an old queue file, the system checks if the object contains the attributes `playlist_strict_mode` and `playlist_item_limit`. If they are not present, it sets them to `False` and `0`, respectively.
Fixes: https://github.com/alexta69/metube/issues/556

Fix: Restore queue when container restarted from old queue file

---

ui/src/custom-service-worker.js

When the path is `/share-target`, `basePath` ends up empty and the `redirect("", 303)` redirects to the JS of the service worker. I got this behaviour on Chrome 135 on MacOS.

Redirect to / when basePath is empty

---

README.md
app/main.py

Some media-indexers create directories (sometimes a lot of them) for thumbnails etc. next to the files. This adds an option to exclude these directories using a regex, which cleans up the drop-down (in my case from >2k to ~30).
Default is set to exclude directories starting with `.` or `@`, which should be quite reasonable for most users. Setting the option to zero-length string disables the filtering and restores the previous behavior.

Add a regex filter to exclude some of the custom directories from the drop-down

---

ui/src/app/app.component.sass

Fix the SASS rule for the app root component not being applied as it was
written for the app root element, not the host scope.
Fixes: d03c710636ccd6db51da1661ddf37ac951577a64

Fix host component style

---

app/ytdl.py

When restoring queued/pending items on restart add the saved details directly to the queue rather than sending them through yt-dlp to re-extract the information we already have. Queues should therefore now load virtually instantaneously.

Improve performance of restoring queued/pending items on restart
