alexta69/metube

README.md, app/main.py, app/ytdl.py
Additional environment variable OUTPUT_TEMPLATE to set an own value for youtube-dl's -o paramter.
=> environment variable to customize output file names

Dockerfile, README.md, app/main.py, app/ytdl.py
=> Add AUDIO_DOWNLOAD_DIR option

README.md
finally i publish extension in store
=> added info in README about browser extension

app/ytdl.py, ui/package-lock.json, ui/package.json, ui/src/app/app.component.html, ui/src/app/app.component.ts, ui/src/app/downloads.service.ts
I added a button to retry failed download 
//cc https://github.com/alexta69/metube/issues/25
https://user-images.githubusercontent.com/265634/127456671-b4e32e51-965a-48d2-b6b1-ae41de76ad70.mov
=> Added retry button for failed download

README.md
Add procedure to use cookies with this container
=> Add cookies how to

ui/src/styles.sass
It will invert the color to make it look dark if your OS selects dark mode. (eg. Windows 10 Settings - Personalization - Colors - App Mode - Dark
#81
=> add a simple dark theme with OS theme

ui/package-lock.json, ui/package.json, ui/src/app/app.component.html, ui/src/app/app.component.sass, ui/src/app/app.component.ts, ui/src/styles.sass
Uses pull #87  as a base. LMK if you want me to change code style as I split things out a bit
=> Made theme toggleable

ui/src/app/app.component.html, ui/src/app/app.component.ts
The Retry-Button from #38  never really worked for me.
Here's a fix that seems to work quite well for me.
In addition I added a Button to navigate to the URL (new tab).
This is helpful if the retry also fails and you would need to do some manual stuff.
=> Fixed Retry Button

app/ytdl.py
Passes playlist parameters to each video 
resolves:
https://github.com/alexta69/metube/issues/107
https://github.com/alexta69/metube/issues/112
=> add playlist parameters

ui/src/app/app.component.html
#175
it's also useful on android
=> add autocomplete="off" spellcheck="false"

app/dl_formats.py
https://github.com/alexta69/metube/issues/188#issuecomment-1363443747
=> convert thumbnail to jpg before embed #188

app/dl_formats.py, app/ytdl.py, ui/src/app/app.component.ts, ui/src/app/formats.ts
Add two more audio formats. Addresses also feature request https://github.com/alexta69/metube/issues/212.
=> Add support for opus and wav

Dockerfile
With this we can execute requests using curl in the postprocessing.
=> Add curl to apk add

ui/src/app/app.component.html, ui/src/app/app.component.ts
This pull request addresses Issue #327 by introducing the ability to retry all failed downloads.
- Adds a "Retry failed" button to handle failed operations.
- Addresses issue #327.
@alexta69  Please test and provide feedback.
=> [feature] Implement "Retry all failed downloads" (#327)

Dockerfile, README.md, app/main.py, ui/src/app/app.component.ts
=> add `PUBLIC_HOST_URL` and `PUBLIC_HOST_AUDIO_URL` config key

app/dl_formats.py
iOS has strict requirements for video files, requiring h264 or h265 video codec and aac audio codec in MP4 container. This update to the MP4 format string tries to get a fully compatible file first, followed by the right video codec and any M4A audio (audio is much faster to convert if needed), and then falls back to the original behaviour of getting the best available MP4 video and M4A audio.
=> Update MP4 format string for iOS compatibility

app/dl_formats.py, ui/src/app/app.component.ts, ui/src/app/formats.ts
=> add flac format for audio

app/ytdl.py
fixes https://github.com/alexta69/metube/issues/497
=> fixed: Regression causing playlist output format to be applied to every video

app/ytdl.py
https://github.com/alexta69/metube/issues/559
=> fix: impersonate property needs to be of the right type and not as it is being passed now via JSON

ui/src/app/app.component.html, ui/src/app/app.component.ts, ui/src/app/downloads.service.ts
Resolves #509. Mostly copies what the "cancel selected" button does. Needed this myself as well, as it makes archiving a user's channel easier.
=> Add a "download selected" button for non-autostarted downloads

ui/src/app/app.component.html, ui/src/app/app.component.ts
=> Download multiple files from MeTube

app/ytdl.py
=> Fix impersonate option

Pipfile, Pipfile.lock
Includes `mutagen` as a dependency in the Pipfile. This should resolve errors experienced when trying to embed thumbnails.
=> Install mutagen

Pipfile.lock
I believe this will fix the [build failure](https://github.com/alexta69/metube/actions/runs/17113355051/job/48539367929).
=> run `pipenv lock` to regenerate lock file

.gitignore
ignore (queue, completed, pending) files
=> Ignore runtime DB files (queue, completed, pending)
